# Generated by Django 6.0.4 on 2026-05-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow_date", models.DateField()),
                ("expected_return", models.DateField()),
                ("actual_return", models.DateField()),
                ("book_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
            ],
            options={
                "ordering": ["borrow_date"],
            },
        ),
    ]
